version: "3.8"

services:
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./downloads:/downloads
    ports:
      - "8080:8080"   # Web UI
      - "6881:6881"   # BitTorrent TCP
      - "6881:6881/udp"
    restart: unless-stopped

  aria2:
    image: p3terx/aria2-pro
    container_name: aria2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - RPC_SECRET=mysecret
    ports:
      - "6800:6800"
      - "6888:6888"
      - "6888:6888/udp"
    volumes:
      - ./aria2/config:/config
      - ./aria2/session:/session
      - ./downloads:/downloads
    restart: unless-stopped

  ariang:
    image: p3terx/ariang
    container_name: ariang
    ports:
      - "6889:8080"
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    user: "1000:1000"
    volumes:
      - ./downloads:/srv
      - ./filebrowser:/config
    ports:
      - "8081:8080"
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./jackett:/config
      - ./downloads:/downloads
    ports:
      - "9117:9117"
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./sonarr:/config
      - ./downloads:/downloads
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./radarr:/config
      - ./downloads:/downloads
    ports:
      - "7878:7878"
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: "1000:1000"
    environment:
      - TZ=Asia/Kolkata
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - ./downloads:/media
    ports:
      - "8096:8096"
    restart: unless-stopped
